% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name test
%  @associatedFile /MATLAB Drive/test.m
%  @mostRecentlyActioned true
%  @uniqueId B026ACCA

test

